### ISSUE TITLE
Suggestions for using AsyncTaskTarget

### ISSUE THREAD

**Issue by snakefoot** [anton-gogolev/nlog.loki#1]
Change `string EndPoint` into `public Layout EndPoint { get; set; }` and replace `ExpandEnvironmentVariables` with `RenderLogEvent(EndPoint, LogEventInfo.CreateNullEvent())`:

https://github.com/anton-gogolev/nlog.loki/blob/90b21ad9444adcb72dcb5fcd2da599a65197f327/src/NLog.Loki/LokiTarget.cs#L20

Remove override of `protected override void Write(IList<AsyncLogEventInfo> logEvents)`:

https://github.com/anton-gogolev/nlog.loki/blob/90b21ad9444adcb72dcb5fcd2da599a65197f327/src/NLog.Loki/LokiTarget.cs#L37

Consider setting Target-property BatchSize = 50 by default:

See also Batch Logic-options: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target#batch-logic

**Comment by anton-gogolev** [comment]
@snakefoot How did you even found out about that project 😅 ?

I don't feel that having an `Endpoint` as `Layout` is good. Layouts are expected to be re-rendered each and every time -- like [`${date}`](https://github.com/NLog/NLog/wiki/Date-Layout-Renderer) for instance. Rendering `Endpoint` only once will be counter-intuitive, and re-rendering it on every write can have significant performance impact because we might be very well connecting to a different URI each time, thus not using HTTP Keep-Alives and the optimizations that `HttpClient` has.

Your other points are valid, but I was unable to get proper batching support during my tests. I'm still investigating that,

**Comment by snakefoot** [comment]
> I don't feel that having an Endpoint as Layout is good. Layouts are expected to be re-rendered each and every time -

Layouts doesn't always have to be rendered for each LogEvent. Especially when making it clear that one uses default-logevent: `RenderLogEvent(EndPoint, LogEventInfo.CreateNullEvent()):`.

> re-rendering it on every write can have significant performance impact because we might be very well connecting to a different URI each time, 

You only have to render it once, when initially creating the EndPoint Layout allows you lookup settings in the environment:

- https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer
- https://github.com/NLog/NLog/wiki/Environment-layout-renderer
- https://github.com/NLog/NLog/wiki/Gdc-Layout-Renderer

**Comment by drbogar** [comment]
Why is this issue still open?

**Comment by snakefoot** [comment]
Closing issue as resolved by 0cc5bee
